spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/h2/bin/testdb;MODE=MYSQL
      driver-class-name: org.h2.Driver
      #    url:
      username: sa
      password: 1111